# Generated by Django 3.1.2 on 2020-10-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('total_cases', models.IntegerField(default='0')),
                ('new_cases', models.IntegerField(default='0')),
                ('total_death', models.IntegerField(default='0')),
                ('new_death', models.IntegerField(default='0')),
                ('total_recovered', models.IntegerField(default='0')),
                ('active_cases', models.IntegerField(default='0')),
                ('serious_critical', models.IntegerField(default='0')),
                ('total_cases_1m_pop', models.IntegerField(default='0')),
                ('deaths_1m_pop', models.IntegerField(default='0')),
                ('total_test', models.IntegerField(default='0')),
                ('test_1m_pop', models.IntegerField(default='0')),
                ('population', models.IntegerField(default='0')),
                ('date', models.DateTimeField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='CountryFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_flag_image', models.FileField(default='some', null=True, upload_to='country_flags')),
                ('country_code', models.CharField(max_length=30)),
            ],
        ),
    ]
