# Generated by Django 3.1 on 2020-10-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_countryflag_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='new_recovered',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_recovered',
            field=models.IntegerField(blank=True),
        ),
    ]
