# Generated by Django 3.1 on 2020-10-10 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20201010_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('c_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.country')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('s_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.state')),
            ],
        ),
    ]
