# Generated by Django 3.1.2 on 2020-10-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_province_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name',
        ),
        migrations.AddField(
            model_name='state',
            name='actuals_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='actuals_contactTracers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='actuals_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='actuals_hospitalBeds_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='actuals_hospitalBeds_currentUsageCovid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='actuals_hospitalBeds_currentUsageTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='actuals_hospitalBeds_typicalUsageRate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='state',
            name='actuals_icuBeds_capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='actuals_icuBeds_currentUsageCovid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='actuals_icuBeds_currentUsageTotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='actuals_icuBeds_typicalUsageRate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='actuals_negativeTests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='actuals_positiveTests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='county',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='state',
            name='fips',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='lastUpdatedDate',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='lat',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='state',
            name='level',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='state',
            name='long',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='state',
            name='metrics_caseDensity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='state',
            name='metrics_contactTracerCapacityRatio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='state',
            name='metrics_icuHeadroomDetails_currentIcuCovid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='metrics_icuHeadroomDetails_currentIcuCovidMethod',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='metrics_icuHeadroomDetails_currentIcuNonCovid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='metrics_icuHeadroomDetails_currentIcuNonCovidMethod',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='metrics_icuHeadroomRatio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='state',
            name='metrics_infectionRate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='state',
            name='metrics_infectionRateCI90',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='state',
            name='metrics_testPositivityRatio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='state',
            name='population',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='state',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
