# Generated by Django 3.1.2 on 2020-10-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20201010_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='actuals_hospitalBeds_capacity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='actuals_hospitalBeds_currentUsageCovid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='actuals_hospitalBeds_currentUsageTotal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='actuals_hospitalBeds_typicalUsageRate',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
