# Generated by Django 3.1.2 on 2020-10-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20201010_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='actuals_hospitalBeds_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='actuals_hospitalBeds_currentUsageCovid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='actuals_hospitalBeds_currentUsageTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='actuals_hospitalBeds_typicalUsageRate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='actuals_icuBeds_capacity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
