# Generated by Django 3.1.2 on 2020-10-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20201010_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='county',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
