# Generated by Django 3.1.2 on 2020-10-11 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20201010_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidRecordUpdateSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(1)])),
                ('hour', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)])),
                ('minutes', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)])),
                ('seconds', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
