# Generated by Django 3.1.2 on 2020-10-11 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_covidrecordupdatesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidrecordupdatesetting',
            name='days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='covidrecordupdatesetting',
            name='hour',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='covidrecordupdatesetting',
            name='minutes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='covidrecordupdatesetting',
            name='seconds',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(0)]),
        ),
    ]
