# Generated by Django 2.2.5 on 2020-10-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_auto_20201011_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidMobility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=120)),
                ('date', models.CharField(blank=True, max_length=120, null=True)),
                ('retailRecreation', models.CharField(default=None, max_length=40, null=True)),
                ('groceryPharmacy', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('parks', models.CharField(default=None, max_length=40, null=True)),
                ('transitStations', models.CharField(default=None, max_length=40, null=True)),
                ('workplaces', models.CharField(default=None, max_length=40, null=True)),
                ('residential', models.CharField(blank=True, max_length=40, null=True)),
                ('diving', models.CharField(blank=True, max_length=40, null=True)),
                ('transit', models.CharField(blank=True, max_length=40, null=True)),
                ('walking', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
