# Generated by Django 2.2.5 on 2020-10-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_covidvaccin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidmobility',
            name='retailRecreation',
            field=models.IntegerField(default=None, max_length=40, null=True),
        ),
    ]
